import './globals.css';
import type { Metadata } from 'next';
import { Syne } from 'next/font/google';
import Container from '../components/Container';

const syne = Syne({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          syne.className + ' bg-dark-base p-3 lg:p-4 w-screen h-screen'
        }
      >
        <Container>{children}</Container>
      </body>
    </html>
  );
}
